name: Deploy lambda

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir lib
        pip install -r requirements.txt --target=lib/
    - name: Test
      run: |
        pip install pytest
        export PYTHONPATH=$PYTHONPATH:$(pwd)/lib
        pytest test/
    - name: Package
      if: success()
      run: |
        zip -ur lys_event_fetcher.zip model/ utils/ main.py
        cd lib
        zip -ur ../lys_event_fetcher.zip *
        cd ..
    - name: Deploy
      if: success()
      uses: stcalica/update-lambda@0.0.2
      with:
        package: lys_event_fetcher.zip
        function-name: LysEventFetcher
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}